[module]
  [module.hugoVersion]
    extended = true
    min = "0.128.0"
[params.head]
    author = "Lanna Caruth"
    description = "Hi, I'm Lanna, and this is my website!"
    keywords = ["Lanna", "Caruth", "portfolio", "website"]

[params.navigation]
    show_navigation = true

[params.footer]
    show_footer = true

[params.typography]
    title_font = "Dosis"
    body_font = "Source Sans Pro"

[params.colors]
    theme_color = "#ef798a"
    background_color = "#ffffff"
    text_color = "#000000"
    link_color = "#7d82b8"

[params.social]
    [params.social.email]
        name = "E-Mail"
        class = "fas fa-envelope"
        url = "mailto:lanna@example.com"
        weight = 1
    [params.social.github]
        name = "GitHub"
        class = "fab fa-github"
        url = "https://github.com/<your_github_username>"
        weight = 2
    [params.social.google_scholar]
        name = "Google Scholar"
        class = "ai ai-google-scholar-square"
        url = "https://scholar.google.com/citations?user=<your_user_id>"
        weight = 3
